### ISSUE TITLE
Reduce number of Reviews in latest reviews component to just one review

### ISSUE THREAD

**Issue by dvidale** [dvidale/python-react-group-proj#171]
Since our reviews are longer than our reference site, let's just put one review in the latest reviews component. That way they don't stretch the page so much.

![Image](https://github.com/user-attachments/assets/53f37131-f7d7-431c-bc55-d8a1f77d4b70)

![Image](https://github.com/user-attachments/assets/1da7556a-0061-4658-aaf2-73d349d01a2a)

**Comment by fullstackneil** [comment]
Added. Tested on render.
